import requests
import json
import random
import html
from tkinter import messagebox

class QuestionGenerator:
    def __init__(self, game):
        self.game = game
        with open('EasyQuestions.json') as f:
            self.data = json.load(f) #This line turns the data taken from the site and loads it into a list
    
    def generateQuestions(self):
        #try:
        #    data = requests.get('https://opentdb.com/api.php?amount=1&difficulty=easy&type=multiple')
        #except requests.exceptions.RequestException:
        #    messagebox.showinfo('Error', 'Could not retrieve questions from Open Trivia API Database. Please check your internet connection.')
        random_index = random.randint(1, len(self.data)-1)
        question_data = self.data['results'][random_index]
        del self.data['results'][random_index]
        question_type = question_data['type'] 
        question = question_data['question'] #Take value question from the list
        question = html.unescape(question) #Turns html entities into unicode symbols
        if question_type == 'multiple': #Multiple choice type questions
            correct_answer = html.unescape(str(question_data['correct_answer'])) #Takes the corrrect answer string varaible from the list generated by the api
            incorrect_answers = question_data['incorrect_answers'] #Takes the incorrect answers list varaible from the api
            answers = incorrect_answers 
            answers.append(correct_answer) #Creates a new list called answers containing both correct and incorrect answers
            random.shuffle(answers) #Randomises the values inside the list
            for i in range(len(answers)): #Turns html entities into unicode symbols for all answers
                answers[i] = html.unescape(answers[i])

        print(question)
        print(correct_answer)
        print(answers)
        return question, correct_answer, answers